### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/San_Francisco_Crime_Resolution_Model#17]
__Mechanics__
- [x] Might want to add version number for the packages in the dependency section.
- [x] Might want to add a link to the final report in README.
- [x] Might want to explain the usage of the scripts a little more. Say, `01_clean_data.py` has three arguments.

__Quality__
- [x] In the documentation at the top of a python or R script, you can explain what the arguments are in addition to showing an usage example.

__Report__
- [x] Would be nice to link the description of variables in Section 1.0 to the variable names in subsequent sections. Say, there are `x` and `y` in Table 2, are they longitude and latitude? 
- [x] Also, I am not 100% sure what is `stolen`, `buliding`, `vehicle` neither when I just look at the Table. Are they among the 50 words extracted? Maybe list these 50 words somewhere?
- [x] How did you choose the depth of your decision tree?
- [x] How did you compute the testing accuracy in section 4.0? 
- [x] Style-wise, would be nice to replace the 'snake_case' with the usual case throughout.

**Comment by ian-flores** [comment]
Hi Eric, between PR #18  and PR #14 we have incorporated most of the points raised in this issue. Just mentioning them here in case you want to take a closer look at it. Ian
